# -*- coding: utf-8 -*-
"""day4_Mehdhat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzqQI_GTFJT4DRiDGN_10-MyTRP1p3eK
"""

import math as mm
print(mm.sqrt(4))

import math
print(math.sqrt(16))
print(math.ceil(2.5))
print(math.floor(2.5))
print(math.factorial(5))
print(math.cos(0))
print(math.sin(0))
print(math.pi)
print(math.exp(3))
print(math.log(10))
print(math.log10(100))
print(math.pow(2,3))
print(math.lcm(10,15))

import datetime
now = datetime.datetime.now()

print(now)

year = now.strftime("%Y")
print("year:" ,year)

month = now.strftime("%B")
print("month:",month)

day = now.strftime("%D")
print("day:",day)

year1 = now.strftime("%y")
print("year1:",year1)

month1 = now.strftime("%b")
print("month1:",month1)

day1 = now.strftime("%d")
print("day1:",day1)

import os
current_dir = os.getcwd()
print(current_dir)

import pickle

# Tuple
my_tuple = (1, 2)


serialized_tuple = open("my_tuple","wb")
pickle.dump(my_tuple,serialized_tuple)
serialized_tuple.close()
print(my_tuple)

deserialized_tuple = open("my_tuple","rb")
my_tuple=pickle.load(deserialized_tuple)
print(my_tuple)

import pickle

# List
my_list = [1, 2]
serialized_list = open("my_list", "wb")
pickle.dump(my_list, serialized_list)
serialized_list.close()


print(my_list)
deserialized_list = open("my_list", "rb")
my_list = pickle.load(deserialized_list)
print(my_list)

import pickle

# Dictionary
my_dictionary = {"name":"mehdhat" ,"age":22}
serialized_dictionary = open("my_dictionary", "wb")
pickle.dump(my_dictionary, serialized_dictionary)
serialized_dictionary.close()

print(my_dictionary)
deserialized_dict = open("my_dictionary", "rb")
my_dictionary = pickle.load(deserialized_dict)
print(my_dictionary)

import os
current_dir = os.getcwd()
print("current directory is" ,current_dir)

#create new directory
new_dir = r"C:\Users\YOU EXCEL\mgdfg"
os.mkdir(new_dir)
print("new directory created" ,new_dir)

#check if a file exists
file_path = r"C:\Users\YOU EXCEL\mgdfg"
if os.path.exists(file_path):
    print("file exists", file_path)
else:
    print("file does not exist", file_path)

#delete directory
delete_dir = r"C:\Users\YOU EXCEL\mgdfg"
os.rmdir(delete_dir)
print("directory deleted", delete_dir)