# -*- coding: utf-8 -*-
"""Assignment 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVCimvHgk7agKfOxlJEQHdhVlxJZTp2m
"""

number= int(input("Enter a number:"))
def prime(number):
  for i in range(2,number):
    if number%i==0:
      print(number,"is not a prime number")
      break
  else:
    print(number,"is a prime number")
prime(number)

lp_year = int(input("Enter year:"))
def leap_year(l_year):
   if lp_year % 4==0:
     print(lp_year,"is a leap year")
   else:
     print(lp_year,"is not a leap year")

leap_year(lp_year)

ele_units = int(input("Enter the number of units:"))
if ele_units <= 200:
   print("Your  bill amount is:", 6000)
elif ele_units <= 300:
  print("Your  bill amount is:", 8000 + 1000)
elif ele_units <= 400:
  print("Your  bill amount is:" ,10000 + 2000)
else:
  print("Your  bill amount is:", 13000 + 3000)