# -*- coding: utf-8 -*-
"""Assignment 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1OznbJQ1WbkRxv_tmYJ4v_1ZG-ksOdL
"""

#Create a Tuple
#Print the length of the tuple
#Print the first and last element of the tuple

new_tuple = (42,"apple",3.14,True)
print(new_tuple)

print(len(new_tuple))

print(new_tuple[0])
print(new_tuple[-1])

#Create two tuples
#Concatenate these two tuples and print the result.
#Repeat tuple1 three times and print the result.

tuple_1 = (10,20,30)
tuple_2 = (40,50,60)

con_mytuples = tuple_1 + tuple_2
print(con_mytuples)

rep_tuple1 = tuple_1 * 3
print(rep_tuple1)

#Create a tuple with three elements: "Python", 5.0, and 2024.
#Unpack the tuple into three variables and print each variable.

tuple = ("Python",5.0,2024)
lang,ver,year = tuple
print(lang)
print(ver)
print(year)

#Create a tuple containing another tuple inside it: ((1, 2, 3), (4, 5, 6)).
#Access and print the element 5 from the nested tuple.

tuple_nes = ((1, 2, 3), (4, 5, 6))
element_5 = tuple_nes[1][1]
print("Element 5 in given tuple is: ", element_5)

#Create a set with the following elements: "apple", "banana", "cherry".
#Add a new element "orange" to the set.
#Remove an element "banana" from the set.
#Check if "cherry" is in the set.

new_set = {"apple", "banana", "cherry"}
print(set)
new_set.add("orange")
print(set)
new_set.remove("banana")
print(set)
if "cherry" in set:
    print("Yes, 'cherry' is in the set.")
else:
    print("No, 'cherry' is not in the set.")

#Create two sets: set1 with elements {1, 2, 3, 4} and set2 with elements {3, 4, 5, 6}.
#Find the union of the two sets and print the result.
#Find the intersection of the two sets and print the result.
#Find the difference between set1 and set2 and print the result.
#Create a set comprehension that generates a set of squares of numbers from 1 to 10.
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
union_set = set1.union(set2)
print(union_set)
intersection_set = set1.intersection(set2)
print(intersection_set)
difference_set = set1.difference(set2)
print(difference_set)
square_num = {i**2 for i in range(1,11)}
print(square_num)